daftar_buku = {
  "Kita Bersama" : "00001"
  "Sabi : Santai di Bali" :"00002"
  "Evaluasi" :"00003"
  "Padahal Kita Sama" :"00004"
  "Kenapa Harus Setara?" :"00005"
  "Dirimu Diriku Diriku Dirimu" :"00006"
  "Secukupnya Saja" :"00007"
  "Pernah Ada di Sampingku" :"00008"
  "Nyata Namun Nyatanya Tiada" :"00009"
  "Kenapa Hasur di Paksa?" :"00010"
  "Palsu"
  "Semuanya Sama Saja"
  "Terhalang Jarak"
  "Memotivasi"
  "lebih Dekat"
  "Setia"
  "Dulu Sangat Indah"
  "Menjadi Dewasa"
  "Aku Sekarang Karena Aku Yang Dulu"
  "Kamu Telah Berubah"
